# Generated by Django 5.1.6 on 2025-02-20 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('a_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('views', models.BigIntegerField()),
                ('likes', models.BigIntegerField()),
                ('shares', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=25)),
                ('c_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comnt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comnt_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('news_content', models.TextField()),
                ('image_url', models.CharField(max_length=500)),
                ('published_date', models.DateField()),
                ('moderation_status', models.CharField(max_length=10)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('pdf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to='news_app.news')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('s_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=40)),
                ('s_url', models.CharField(max_length=100)),
                ('s_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('preference_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('admin', 'Admin')], max_length=50)),
                ('phn_no', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('u_status', models.CharField(default='active', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsPDF',
        ),
        migrations.AddField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.news'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.news'),
        ),
        migrations.AddField(
            model_name='news',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.source'),
        ),
    ]
